export let coachesData = [
    {
    id: "1",
    name: "Khamis Hassan",
    nameAr: "خميس حسن",
    title: "Swimming & Fitness Coach",
    titleAr: "مدرب سباحة ولياقة بدنية",
    bio: "Certified swimming and fitness coach specialized in fins swimming and bodybuilding training with strong experience in youth and adults coaching.",
    bioAr: "مدرب سباحة ولياقة بدنية معتمد متخصص في تدريب السباحة بالزعانف وكمال الأجسام ولديه خبرة قوية في تدريب الناشئين والكبار.",
    specialization: "swimming",
    image: null,
    experience: "8",
    students: "200",
    certifications: "4",
    rating: "4.8",
    specializations: ["Fins Swimming", "Fitness Training", "Bodybuilding"],
    achievements: [
      "Certified Fins Swimming Coach",
      "Youth Swimming Trainer",
      "Fitness Program Designer"
    ],
    email: "",
    phone: ""
  },
  {
    id: "2",
    name: "Fares Sheta",
    nameAr: "فارس شتا",
    title: "Swimming Coach",
    titleAr: "مدرب سباحة",
    bio: "Young swimming coach specialized in kids and beginners training using scientific and safe training methods.",
    bioAr: "مدرب سباحة متخصص في تدريب الأطفال والمبتدئين باستخدام أساليب تدريب علمية وآمنة.",
    specialization: "swimming",
    image: null,
    experience: "2",
    students: "120",
    certifications: "5",
    rating: "4.7",
    specializations: ["Kids Swimming", "Beginner Training", "Water Safety"],
    achievements: [
      "CPR & First Aid Certified",
      "Sports Nutrition Course",
      "Injury Prevention Training"
    ],
    email: "",
    phone: ""
  },
  {
    id: "3",
    name: "Abdelwahab Ibrahim",
    nameAr: "عبدالوهاب إبراهيم",
    title: "Swimming Coach & Sports Therapist",
    titleAr: "مدرب سباحة وأخصائي إصابات رياضية",
    bio: "Certified swimming coach and sports injury specialist with experience in rehabilitation, massage therapy and athletic performance development.",
    bioAr: "مدرب سباحة معتمد وأخصائي إصابات رياضية يمتلك خبرة في التأهيل الرياضي والتدليك وتطوير الأداء البدني.",
    specialization: "swimming",
    image: null,
    experience: "7",
    students: "180",
    certifications: "6",
    rating: "4.8",
    specializations: ["Swimming Coaching", "Sports Rehabilitation", "Sports Nutrition"],
    achievements: [
      "Rescue Certificate Holder",
      "Sports Medicine Specialist",
      "Load Planning Course"
    ],
    email: "",
    phone: ""
  },
  {
    id: "4",
    name: "Amani Ahmed",
    nameAr: "أماني أحمد",
    title: "Swimming & Aerobic Gymnastics Coach",
    titleAr: "مدربة سباحة وجمباز أيروبك",
    bio: "Certified aerobic gymnastics and swimming coach experienced in training kids, special needs athletes and fitness programs.",
    bioAr: "مدربة سباحة وجمباز أيروبك معتمدة ولديها خبرة في تدريب الأطفال وذوي الاحتياجات الخاصة وبرامج اللياقة.",
    specialization: "gymnastics",
    image: null,
    experience: "6",
    students: "150",
    certifications: "5",
    rating: "4.9",
    specializations: ["Aerobic Gymnastics", "Kids Training", "Rehabilitation"],
    achievements: [
      "Egyptian Gymnastics Federation Certified",
      "Sports for All Program Trainer",
      "Motor Rehabilitation Course"
    ],
    email: "",
    phone: ""
  },
  {
    id: "5",
    name: "Mostafa Farag",
    nameAr: "مصطفى فرج",
    title: "Head Swimming Coach",
    titleAr: "المدير الفني للسباحة",
    bio: "Head swimming coach and international water safety instructor with extensive experience in performance training and athletic preparation.",
    bioAr: "المدير الفني للسباحة ومدرب إنقاذ وسلامة مائية دولي يمتلك خبرة كبيرة في إعداد السباحين وتطوير الأداء الرياضي.",
    specialization: "swimming",
    image: null,
    experience: "12",
    students: "350",
    certifications: "8",
    rating: "5.0",
    specializations: ["Competitive Swimming", "Water Safety", "Fitness Training"],
    achievements: [
      "International Water Safety Instructor",
      "African Sports First Aid Certificate",
      "Military Academy Trainer"
    ],
    email: "",
    phone: ""
  },
  {
    id: "6",
    name: "Nesreen Osman",
    nameAr: "نسرين عثمان",
    title: "Swimming & Artistic Gymnastics Coach",
    titleAr: "مدربة سباحة وجمباز فني",
    bio: "Experienced swimming and artistic gymnastics coach who participated in national championships and youth training programs.",
    bioAr: "مدربة سباحة وجمباز فني تمتلك خبرة في البطولات المحلية وبرامج تدريب الناشئين.",
    specialization: "gymnastics",
    image: null,
    experience: "10",
    students: "220",
    certifications: "6",
    rating: "4.8",
    specializations: ["Artistic Gymnastics", "Swimming Training", "Sports Shows"],
    achievements: [
      "National Gymnastics Championships Participant",
      "Gymnastics Federation Certified",
      "Motor Rehabilitation Course"
    ],
    email: "",
    phone: ""
  },
  {
    id: "7",
    name: "Nahla Maher",
    nameAr: "نهلة ماهر",
    title: "Club Technical Director",
    titleAr: "المدير الفني للنادي",
    bio: "Technical director specialized in sports management, gymnastics development and organizing sports championships.",
    bioAr: "مدير فني متخصص في الإدارة الرياضية وتطوير الجمباز وتنظيم البطولات الرياضية.",
    specialization: "management",
    image: null,
    experience: "14",
    students: "400",
    certifications: "5",
    rating: "4.9",
    specializations: ["Sports Management", "Gymnastics Programs", "Leadership"],
    achievements: [
      "Handball Referee Course",
      "Sports Shows Organizer",
      "Leadership Training Certificate"
    ],
    email: "",
    phone: ""
  },
  {
    id: "8",
    name: "Fathallah Nawar",
    nameAr: "فتح الله نوار",
    title: "Swimming Coach",
    titleAr: "مدرب سباحة",
    bio: "Experienced swimming coach focused on building correct swimming fundamentals for different age groups.",
    bioAr: "مدرب سباحة يمتلك خبرة في تأسيس مهارات السباحة الصحيحة لمختلف المراحل العمرية.",
    specialization: "swimming",
    image: null,
    experience: "9",
    students: "210",
    certifications: "3",
    rating: "4.7",
    specializations: ["Beginner Swimming", "Technique Training", "Kids Training"],
    achievements: [
      "Senior Physical Education Teacher",
      "Youth Swimming Trainer",
      "Technique Specialist"
    ],
    email: "",
    phone: ""
  },
  {
    id: "9",
    name: "Hany Shehab",
    nameAr: "هاني شهاب",
    title: "Taekwondo Coach",
    titleAr: "مدرب تايكوندو",
    bio: "Taekwondo coach specialized in discipline training, self-defense and physical conditioning.",
    bioAr: "مدرب تايكوندو متخصص في تدريب الانضباط والدفاع عن النفس والإعداد البدني.",
    specialization: "martial-arts",
    image: null,
    experience: "8",
    students: "170",
    certifications: "4",
    rating: "4.8",
    specializations: ["Taekwondo Basics", "Self Defense", "Fitness"],
    achievements: [
      "Martial Arts Trainer",
      "Kids Discipline Programs",
      "Physical Conditioning Specialist"
    ],
    email: "",
    phone: ""
  },
  {
    id: "10",
    name: "Mahmoud Fathy",
    nameAr: "محمود فتحي",
    title: "Gymnastics & Taekwondo Coach",
    titleAr: "مدرب جمباز وتايكوندو",
    bio: "Artistic gymnastics coach and taekwondo assistant trainer focused on physical preparation and performance improvement.",
    bioAr: "مدرب جمباز فني ومدرب مساعد تايكوندو متخصص في الإعداد البدني وتطوير الأداء الرياضي.",
    specialization: "gymnastics",
    image: null,
    experience: "5",
    students: "140",
    certifications: "4",
    rating: "4.7",
    specializations: ["Artistic Gymnastics", "Physical Preparation", "Taekwondo"],
    achievements: [
      "Gymnastics Refereeing Course",
      "First Aid Certificate",
      "Sports Massage Course"
    ],
    email: "",
    phone: ""
  }
];